<template>
  <section class="admin-content">
    <el-card class="panel" shadow="never">
      <div class="panel-header">
        <div class="panel-title">提醒类型管理</div>
        <el-space wrap>
          <el-button type="primary" plain @click="$emit('open-create')">新增提醒类型</el-button>
        </el-space>
      </div>
      <el-table :data="reminderTypeData" size="small" border stripe>
        <el-table-column prop="reminderTypeId" label="ID" width="80" />
        <el-table-column prop="typeName" label="提醒名称" width="160" />
        <el-table-column prop="sourceTable" label="来源表" width="160" />
        <el-table-column prop="sourceField" label="字段" width="140" />
        <el-table-column prop="advanceDays" label="提前天数" width="120" />
        <el-table-column prop="templateMessage" label="模板消息" />
        <el-table-column prop="autoGenerated" label="自动生成" width="110">
          <template #default="{ row }">
            {{ row.autoGenerated ? '是' : '否' }}
          </template>
        </el-table-column>
        <el-table-column label="操作" width="140" fixed="right">
          <template #default="{ $index, row }">
            <el-button size="small" type="primary" link circle @click="$emit('open-edit', $index)">
              <el-icon><Edit /></el-icon>
            </el-button>
            <el-button size="small" type="danger" link circle @click="$emit('remove', $index, row)">
              <el-icon><Delete /></el-icon>
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>
  </section>
</template>

<script setup>
defineProps({
  reminderTypeData: { type: Array, default: () => [] }
})

defineEmits(['open-create', 'open-edit', 'remove'])
</script>

<style scoped>
.panel-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 12px;
  gap: 12px;
  flex-wrap: wrap;
}
</style>
